name: Accessibility Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # Run every Monday at midnight

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Install axe-cli
        run: npm install -g @axe-core/cli
      - name: Start server
        run: npm run serve:dist & sleep 10
      - name: Run axe accessibility tests
        run: axe http://localhost:3000 --exit
